package com.smore.payment.payment.infrastructure.persistence.mongo.model;

public enum PaymentAuditEventType {
    TEMPORARY_PAYMENT_CREATED,
    PAYMENT_APPROVAL_REQUESTED,
    PG_APPROVAL_REQUESTED,
    PG_APPROVAL_SUCCEEDED,
    PG_APPROVAL_FAILED,
    PAYMENT_APPROVAL_SUCCEEDED,
    PAYMENT_APPROVAL_FAILED,
    PAYMENT_REFUND_REQUESTED,
    PG_REFUND_REQUESTED,
    PG_REFUND_SUCCEEDED,
    PG_REFUND_FAILED,
    PAYMENT_REFUND_SUCCEEDED,
    PAYMENT_REFUND_FAILED
}